### PR TITLE
Extended import functionality to include Mura destination + more

### PR DESCRIPTION
**Pull request by JasPanesar**
Greg,

Added some more import functionality, seems to work good for me.  I'll try to get the dates importing as well.

This should resolve a few of the issues in the main repo.  Let me know if you have any questions.

### CODE REVIEW

**Comment by gregmoser** [comment]
Hey Jas, it looks like a while back I started a develop branch.  at this point I'm not sure why I made those changes... I was wondering if you could review develop in comparison with you branch to see if there are any features I added there that would be useful.

While it's fresh in your mind you'll probably have a better idea of what I was trying to do.

**Comment by JasPanesar** [comment]
Fresh in my head indeed -- it looks like you tackled importing comments.  I didn't touch that at all, however I'd like to be able to turn comment importing on or off (I have a lot of comment spam, for example I don't want in Mura).

Also,the category importing seems to not work with the older wordpress versions so I'd probably want to make that a checkbox to turn it on or off if that's ok with you.

**Comment by gregmoser** [comment]
Yes! absolutely... just make them settings, and add it to you fork.  then I can trash the develop branch and merge yours into master.

**Comment by JasPanesar** [comment]
Sounds good.

**Comment by JasPanesar** [comment]
Greg, I've merged the changes from devel into this to the best of my awareness.  Also implemented the checkbox on whether to attempt bringing in categories, or not, which is not working for me (not sure why, my WP install might be a little too old).

The Comments stuff is now there in wordpress.cfc but not turned on by default until there's a chance to test it.  I was going to mark it experimental but I'm pretty sure I mucked up the migration of the code into the file.  Have a quick peek in case I messed up the syntax.

Otherwise, I completed an import using this version just now and things seem to be good.

**Pull request merged**
